### PR TITLE
fix dl linking for liblttng-ust-tracepoint and liblttng-ust

### PR DESCRIPTION
**Pull request by vitlav**
Signed-off-by: Vitaly Lipatov <lav@etersoft.ru>

### CODE REVIEW

**Comment by compudj** [comment]
In the patch commit message, please mention which platform(s) are affected by this problem (or at least on which platform you reproduce it).

**Comment by vitlav** [comment]
I guess nobody on your side do know a platform I reproduce on. It is ALT distro.
First part of the patch fix dl underlinking in liblttng-ust-tracepoint (it uses dopen/dlfree), secord part fix forced -ldl linking (missed on FreeBSD).
TYis patch like a typo fix, means for any platform.

**Comment by compudj** [comment]
So what you are describing here is that the original "-ldl" is kept in liblttng_ust_la_LIBADD, but it now uses the LTTNG_UST_BUILD_WITH_LIBDL/LIBC_DL variables to choose between -ldl and -lc. This is a first fix for distributions that use LIBC_DL.

The second fix there is adding a missing direct dependency against -ldl or -lc to liblttng_ust_tracepoint_la_LIBADD, given that it uses dlopen/dlclose. Indeed, the __tracepoints__init() constructor in tracepoint.h currently uses dlopen even for files that define _LGPL_SOURCE (which I think was not the case a few years ago).

This patch is really not a simple typo fix. It actually fixes two makefile issues and deserves to have all this documented in its commit message.

**Comment by vitlav** [comment]
Please, help me write clean description of this commit. Can I use your detailed description in it?

**Comment by compudj** [comment]
Sure, feel free to use my description.

**Comment by vitlav** [comment]
Will somebody care about that changes?

**Comment by compudj** [comment]
Merged manually into the master branch, stable-2.10 and stable-2.9 branches.

Thanks!

Mathieu

**Pull request closed without merging**
