### PR TITLE
Java filter notification mechanism

### PR DESCRIPTION
**Pull request by alexmonthy**
New tests were added to https://github.com/alexmonthy/ust-java-tests to cover the new functionality. Corresponding CI run at: https://ci.lttng.org/view/alexmonthy/job/ust-java-tests-staging-alexmonthy/45/

### CODE REVIEW

**Comment by alexmonthy** [comment]
Note this does not include the "filter string" element of event rules, because the sessiond does not currently send it. I will do another patch to add the filter string once it's added on the lttng-tools side.

**Comment by alexmonthy** [comment]
I have pushed a new version of the branch.

Changes since the previous version:
* Renamed LogLevelFilter -> LogLevelSelector
* Renamed FilterNotificationManager -> FilterChangeNotifier (more in line with IFilterChangeListener)
* Clarified the if/elseif's in equals() methods. Now with more brackets.
* Listeners now receive the current state upon registration
* Made the whole notifier synchronized

Also added a test to verify the "statedump" to the test suite.
Latest run: https://ci.lttng.org/view/alexmonthy/job/ust-java-tests-staging-alexmonthy/46/

**Comment by alexmonthy** [comment]
Thanks for the review! I've fixed the comments, and as we discussed, I added in here the patch to update to the 1.1 agent protocol. This PR is now dependant on https://github.com/lttng/lttng-tools/pull/42 getting into tools first.

**Comment by alexmonthy** [comment]
Update to the latest commit: the protocol version is now 2.0, and it should handle the (hopefully rare) case where the filter string length is between 2^31 and 2^32.

**Comment by compudj** [comment]
----- On Sep 13, 2015, at 7:20 PM, alexmonthy <notifications@github.com> wrote: 

> Update to the latest commit: the protocol version is now 2.0, and it should
> handle the (hopefully rare) case where the filter string length is between 2^31
> and 2^32.
Did you test that the conversion don't sign-extend when casting 
to 64-bit signed integer ? 

Why are two arrays needed ? 

Thanks, 

Mathieu 

> —
> Reply to this email directly or view it on GitHub .

-- 
Mathieu Desnoyers 
EfficiOS Inc. 
http://www.efficios.com

**Comment by alexmonthy** [comment]
On 2015-09-13 08:51 PM, Mathieu Desnoyers wrote:
> ----- On Sep 13, 2015, at 7:20 PM, alexmonthy <notifications@github.com> wrote:
>
>> Update to the latest commit: the protocol version is now 2.0, and it should
>> handle the (hopefully rare) case where the filter string length is between 2^31
>> and 2^32.
> Did you test that the conversion don't sign-extend when casting
> to 64-bit signed integer ?

I tested the "usual" case, and the length and string are read correctly.

I have not yet tested the case where the filter string is greater than 2 
GB, but I'm planning to add a test for that.
>
> Why are two arrays needed ?

You can't have [] arrays with long indexes in Java, only (signed) int is 
permitted. For the case where the total length is greater than 
Integer.MAX_VALUE (2^31 - 1) we have to do two separate calls to 
ByteBuffer.get(byte[]).

**Comment by compudj** [comment]
----- On Sep 13, 2015, at 9:24 PM, alexmonthy <notifications@github.com> wrote: 

> On 2015-09-13 08:51 PM, Mathieu Desnoyers wrote:
> > ----- On Sep 13, 2015, at 7:20 PM, alexmonthy <notifications@github.com> wrote:

> >> Update to the latest commit: the protocol version is now 2.0, and it should
> >> handle the (hopefully rare) case where the filter string length is between 2^31
> >> and 2^32.
> > Did you test that the conversion don't sign-extend when casting
> > to 64-bit signed integer ?

> I tested the "usual" case, and the length and string are read correctly.

> I have not yet tested the case where the filter string is greater than 2
> GB, but I'm planning to add a test for that.

> > Why are two arrays needed ?

> You can't have [] arrays with long indexes in Java, only (signed) int is
> permitted. For the case where the total length is greater than
> Integer.MAX_VALUE (2^31 - 1) we have to do two separate calls to
> ByteBuffer.get(byte[]).
We'd actually need 2^32 arrays in the worst case, not 2. 

Hrm, considering all those limitations, it might make sense to impose 
a rather large limit on the string length. 

Thoughts ? 

Thanks, 

Mathieu 


> > Thanks,

> > Mathieu

> >> —
> >> Reply to this email directly or view it on GitHub .

> —
> Reply to this email directly or view it on GitHub .

-- 
Mathieu Desnoyers 
EfficiOS Inc. 
http://www.efficios.com

**Comment by alexmonthy** [comment]
>> You can't have [] arrays with long indexes in Java, only (signed) int is
>> permitted. For the case where the total length is greater than
>> Integer.MAX_VALUE (2^31 - 1) we have to do two separate calls to
>> ByteBuffer.get(byte[]).
> We'd actually need 2^32 arrays in the worst case, not 2.
>
> Hrm, considering all those limitations, it might make sense to impose
> a rather large limit on the string length.
>
> Thoughts ?

Yes, in fact it turns out that since String is backed by a char[], a 
single String can't have more than (2^32 -1) characters either. So I 
think that should be the upper limit on what the Java agent supports.

So, should the Java agent check for the length, and return a command 
error if the filter string is too long? Or would there be a guaranteed 
size limit on the sessiond side too?

**Comment by alexmonthy** [comment]
After discussion, we've decided to put a limit on the size of the filter string. With the new version, if the length is too long, the agent will return a command error.

**Comment by PSRCode** [comment]
@alexmonthy what is the status of this ?

**Comment by alexmonthy** [comment]
It's still waiting on https://github.com/lttng/lttng-tools/pull/42 . This patch bumps the agent protocol version to 2.0, and that PR for tools does the corresponding updates.

**Pull request closed without merging**
